config/routes.rb
LOGOAnalyst::Application.routes.draw do

  resources :global_companies

  resources :companies

  match '/companies/new_random_profile' => 'companies#new_random_profile'

  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users

  resources :users

  resources :surveys

  resources :questions

  get "home/index"
  root :to => 'home#index'

  resources :experiments

  match ':controller(/:action(/:id))(.:format)'
end

app/models/experiment.rb
class Experiment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :times, type: Integer
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.json
  def new
    @experiment = Experiment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.haml
= form_for @experiment, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :_type, :class => 'control-label'
    .controls
      = f.text_field :_type, :class => 'text_field'
  .control-group
    = f.label :_id, :class => 'control-label'
    .controls
      = f.text_field :_id, :class => 'text_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :times, :class => 'control-label'
    .controls
      = f.text_field :times, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), experiments_path, :class => 'btn'

app/views/experiments/edit.html.haml
- model_class = Experiment
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/experiments/index.html.haml
- model_class = Experiment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:times)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @experiments.each do |experiment|
      %tr
        %td= link_to experiment.name, experiment_show_path(experiment)
        %td= experiment.times
        %td=l experiment.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_experiment_path(experiment), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), experiment_path(experiment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_experiment_path, :class => 'btn btn-primary'

app/views/experiments/new.html.haml
- model_class = Experiment
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/experiments/show.html.haml
- model_class = Experiment
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:_type) + ':'
  %br
  = @experiment._type
%p
  %strong= model_class.human_attribute_name(:_id) + ':'
  %br
  = @experiment._id
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @experiment.name
%p
  %strong= model_class.human_attribute_name(:times) + ':'
  %br
  = @experiment.times

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), experiments_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_experiment_path(@experiment), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), experiment_path(@experiment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'