config/routes.rb
LOGOAnalyst::Application.routes.draw do

  resources :global_companies

  resources :companies

  match '/companies/new_random_profile' => 'companies#new_random_profile'

  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users

  resources :users

  resources :surveys

  resources :questions

  get "home/index"
  root :to => 'home#index'

  resources :experiments

  match ':controller(/:action(/:id))(.:format)'
end

app/models/survey.rb
class Survey
  include Mongoid::Document
  include Mongoid::Timestamps

  field :other, type: String

  belongs_to :profile
  belongs_to :answer

  #TODO minimize database problem
  after_create :inc_count
  after_destroy :dec_count

  def inc_count
    Question.where('answers._id' => Moped::BSON::ObjectId(self.answer_id))[0].answers.where(:id => self.answer_id).first.inc(:counter, 1)
    Company.where('profiles._id' => Moped::BSON::ObjectId(self.profile_id))[0].profiles.where(:id => self.profile_id).first.inc(:counter, 1)
  end

  def dec_count
    Company.where('profiles._id' => Moped::BSON::ObjectId(self.profile_id))[0].profiles.where(:id => self.profile_id).first.inc(:counter, -1)
    Question.where('answers._id' => Moped::BSON::ObjectId(self.answer_id))[0].answers.where(:id => self.answer_id).first.inc(:counter, -1)
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  before_filter :init

  def index

  end


  def list
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new


    # randomly select an existing company profile with the least response

    # display this profile and all questions
    @surveys = Array.new
    @questions.count.times do
      @surveys << @profile.surveys.build
    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create

    @profile.assign_attributes(params[:profile])

    #TODO redirection problem
    respond_to do |format|
      if @profile.save
        format.html { redirect_to root_path, notice: 'Response was successfully sent, thank you very much for participation.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update


    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end


  def init
    @profile ||= Company.profile_with_least_survey
    @questions ||= Question.all.to_a

  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Company:
      %th Symbol:
      %th Website:
      %th Logo:
  %tbody
    %tr
      %td= @profile.company.name
      %td= @profile.company.symbol
      %td= @profile.url
      - if @profile.logo.url != nil
        %td= image_tag(@profile.logo.url)
      - else
        %td None

-# TODO set profile.id into user's cookies


= simple_form_for @profile, url: {controller: "surveys" ,action: "create"}, :method => :post do |f|
  - @surveys.each.with_index do |survey, index|
    = f.simple_fields_for :surveys, survey do |fs|
      = @questions[index].question_content
      = fs.association :answer, :collection => @questions[index].answers, :as => :radio_buttons, :item_wrapper_class => 'inline',:label => '', :label_method => :answer_content
      %hr




  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.back', :default => t("helpers.links.back")), {:action => "index"}, { :class => 'btn'}

app/views/surveys/edit.html.haml
- model_class = Survey
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/surveys/index.html.haml
= link_to t('.new', :default => t("helpers.links.new")), new_survey_path, :class => 'btn btn-primary'

app/views/surveys/list.html.haml
- model_class = Survey
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:_type)
      %th= model_class.human_attribute_name(:_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @surveys.each do |survey|
      %tr
        %td= link_to survey.id, survey_path(survey)
        %td= survey._type
        %td= survey._id
        %td=l survey.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_survey_path(survey), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), survey_path(survey), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_survey_path, :class => 'btn btn-primary'

app/views/surveys/new.html.haml
- model_class = Survey
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")



= render :partial => "form"

app/views/surveys/show.html.haml
- model_class = Survey
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:_type) + ':'
  %br
  = @survey._type
%p
  %strong= model_class.human_attribute_name(:_id) + ':'
  %br
  = @survey._id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), surveys_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_survey_path(@survey), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), survey_path(@survey), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'