config/routes.rb
LOGOAnalyst::Application.routes.draw do

  resources :global_companies

  resources :companies

  match '/companies/new_random_profile' => 'companies#new_random_profile'

  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users

  resources :users

  resources :surveys

  resources :questions

  get "home/index"
  root :to => 'home#index'

  resources :experiments

  match ':controller(/:action(/:id))(.:format)'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps


  field :answer_content, type: String

  embedded_in :question
  has_many :surveys


  include Counter
  after_create :inc_count
  after_destroy :dec_count


end

app/models/company.rb
class Company
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :symbol, type: String

  belongs_to :sector
  embeds_many :profiles, cascade_callbacks: true


  class << self
    def random(n = 1)
      no_profile_company = Company.any_in("profiles" => nil)
      indexes = (0..no_profile_company.count-1).sort_by { rand }.slice(0, n)
      if n == 1
        return self.skip(indexes.first).first
      else
        return indexes.map { |index| self.skip(index).first }
      end

    end

    def profile_with_least_survey
      Company.any_of(:profiles.exists => true).all.asc('profiles.counter').limit(1).first.profiles.asc(:counter).limit(1).first
    end
  end
end

app/models/country.rb
class Country
  include Mongoid::Document
  include Mongoid::Timestamps


  field :name, type: String

  has_many :global_companies

end

app/models/experiment.rb
class Experiment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :times, type: Integer
end

app/models/global_company.rb
class GlobalCompany
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :symbol, type: String

  belongs_to :country
  belongs_to :global_industry
  has_many :global_company_profiles


  accepts_nested_attributes_for :global_company_profiles
  after_create :inc_count
  after_destroy :dec_count

  def inc_count
    self.country.inc(:counter, 1)
    self.global_industry.inc(:counter, 1)
  end

  def dec_count
    self.country.inc(:counter, -1)
    self.global_industry.inc(:counter, -1)
  end
end

app/models/global_industry.rb
class GlobalIndustry
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_many :global_companies
end

app/models/industry_group.rb
class IndustryGroup
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String


  has_many :sectors
end

app/models/profile.rb
class Profile
  include Mongoid::Document
  include Mongoid::Timestamps
  field :url, type: String
  field :beginning, type: Date
  field :ending, type: Date


  mount_uploader :logo, LogoUploader


  embedded_in :company
  has_many :surveys

  accepts_nested_attributes_for :surveys

  include Counter
  after_create :inc_count
  after_destroy :dec_count


end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  field :question_content, type: String

  embeds_many :answers, cascade_callbacks: true

  accepts_nested_attributes_for :answers, :allow_destroy => true, :reject_if => lambda { |a| a[:answer_content].blank? }
end

app/models/question_type.rb
class QuestionType
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  # To change this template use File | Settings | File Templates.
end

app/models/response.rb
class Response
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :other, type: String

  belongs_to :answer
  embedded_in :survey

end

app/models/role.rb
class Role
  include Mongoid::Document

  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true

  field :name, :type => String
  index({:name => 1}, {:unique => true})


  index({
            :name => 1,
            :resource_type => 1,
            :resource_id => 1
        },
        {:unique => true})

  scopify
end

app/models/sector.rb
class Sector
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  belongs_to :industry_group
  has_many :companies


end

app/models/survey.rb
class Survey
  include Mongoid::Document
  include Mongoid::Timestamps

  field :other, type: String

  belongs_to :profile
  belongs_to :answer

  #TODO minimize database problem
  after_create :inc_count
  after_destroy :dec_count

  def inc_count
    Question.where('answers._id' => Moped::BSON::ObjectId(self.answer_id))[0].answers.where(:id => self.answer_id).first.inc(:counter, 1)
    Company.where('profiles._id' => Moped::BSON::ObjectId(self.profile_id))[0].profiles.where(:id => self.profile_id).first.inc(:counter, 1)
  end

  def dec_count
    Company.where('profiles._id' => Moped::BSON::ObjectId(self.profile_id))[0].profiles.where(:id => self.profile_id).first.inc(:counter, -1)
    Question.where('answers._id' => Moped::BSON::ObjectId(self.answer_id))[0].answers.where(:id => self.answer_id).first.inc(:counter, -1)
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email, :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  field :name, :type => String, :default => ""


  validates_presence_of :name, :email, :encrypted_password
  validates_uniqueness_of :name, :email, :case_sensitive => false

  ## Recoverable
  field :reset_password_token, :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count, :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at, :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CORPORATE LOGO ANALYSIS"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    -#%link(href="images/favicon.ico" rel="shortcut icon")


  %body
    #wrapper
      .navbar.navbar-fixed-top
        .navbar-inner
          .container-fluid
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            .brand=link_to "Corporate Logo Analysis", root_path

            .btn-group.pull-right
              %a.btn.dropdown-toggle(data-toggle="dropdown" href="#")
                %i.icon-user
                Username
                %span.caret
              - if current_user.blank?
                %ul.dropdown-menu
                  %li
                    %a=link_to "Sign in", new_user_session_path, :method => :get
                  %li.divider
                  %li
                    %a=link_to "Sign up", new_user_registration_path, :method => :get
              - else
                %ul.nav
                  %li
                    %a(href="#") Profile
                  %li.divider
                  %li
                    %a=link_to "Sign out", destroy_user_session_path, :method => :delete

            .nav-collapse
              %ul.nav.nav-tabs
                %li{class: ("active" if params[:controller] == 'home')}
                  =link_to "Home", root_path
                %li.dropdown{class: ("active" if params[:controller] == 'companies' || params[:controller] == 'global_companies')}
                  %a.dropdown-toggle{"data-toggle" =>"dropdown", :href => "#"}
                    Company
                    %b.caret
                  %ul.dropdown-menu
                    %li=link_to "Thai Top 100 Companies", companies_path
                    %li=link_to "Global Top 200 Companies", global_companies_path
                %li.dropdown{class: ("active" if params[:controller] == 'questions' || params[:controller] == 'surveys')}
                  %a.dropdown-toggle{"data-toggle" =>"dropdown", :href => "#"}
                    Survey
                    %b.caret
                  %ul.dropdown-menu
                    %li=link_to "Manage Survey", questions_path
                    %li=link_to "Response", new_survey_path

      .container-fluid

        .row-fluid

          .span3


            .well.sidebar-nav.sidebar-nav-fixed

              = yield :sidebar
              %hr
              %ul.nav.nav-list
                %li.nav-header Links
                %li= link_to "Top Global Companies", global_companies_path
                %li= link_to "Top Thai Companies", companies_path
                %li= link_to "Forbes Global Leading Companies", "http://www.forbes.com/global2000/list"

                %li= link_to "Brands of the World", "http://www.brandsoftheworld.com/"
                %li= link_to "Logopedia", "http://logos.wikia.com/wiki/Logopedia"
                %li= link_to "Fonts.com", "http://www.fonts.com/"
                %li= link_to "ColorWheel", "http://www.ficml.org/jemimap/style/color/wheel.html"


          .span9
            = bootstrap_flash
            = yield

        #push

    %footer#footer
      %hr
      %small BUUIC RESEARCH CENTER 2012
      %br
      %small Programed by Orion Chang
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


    :javascript
      $(document).ready(function(){
        $('#button').button();

        $('#button').click(function() {
          $(this).button('loading');
        });
      });